In [4]:
import pandas as pd

In [5]:
import numpy as np

In [360]:
import math as m
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn import naive_bayes
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
import csv
import warnings
warnings.filterwarnings("ignore")
from sklearn.model_selection import cross_val_score

In [310]:
cleveland_data = pd.read_csv("cleveland.csv", header= None)

In [311]:
statlog_data = pd.read_csv("statlog.csv", header= None, sep=" ")

In [312]:
cleveland_data.tail()

0    1    2      3      4    5    6      7    8    9    10   11   12  \
298  45.0  1.0  1.0  110.0  264.0  0.0  0.0  132.0  0.0  1.2  2.0  0.0  7.0   
299  68.0  1.0  4.0  144.0  193.0  1.0  0.0  141.0  0.0  3.4  2.0  2.0  7.0   
300  57.0  1.0  4.0  130.0  131.0  0.0  0.0  115.0  1.0  1.2  2.0  1.0  7.0   
301  57.0  0.0  2.0  130.0  236.0  0.0  2.0  174.0  0.0  0.0  2.0  1.0  3.0   
302  38.0  1.0  3.0  138.0  175.0  0.0  0.0  173.0  0.0  0.0  1.0    ?  3.0   

     13  
298   1  
299   2  
300   3  
301   1  
302   0

In [313]:
cleveland_data.columns = [ 'age','sex','cp','thestbps','chol','restecg','fbs','thalach','exang','oldpeak','slope','ca','thal','label']

In [314]:
cleveland_data.head()

age  sex   cp  thestbps   chol  restecg  fbs  thalach  exang  oldpeak  \
0  63.0  1.0  1.0     145.0  233.0      1.0  2.0    150.0    0.0      2.3   
1  67.0  1.0  4.0     160.0  286.0      0.0  2.0    108.0    1.0      1.5   
2  67.0  1.0  4.0     120.0  229.0      0.0  2.0    129.0    1.0      2.6   
3  37.0  1.0  3.0     130.0  250.0      0.0  0.0    187.0    0.0      3.5   
4  41.0  0.0  2.0     130.0  204.0      0.0  2.0    172.0    0.0      1.4   

   slope   ca thal  label  
0    3.0  0.0  6.0      0  
1    2.0  3.0  3.0      2  
2    2.0  2.0  7.0      1  
3    3.0  0.0  3.0      0  
4    1.0  0.0  3.0      0

In [315]:
statlog_data.columns = [ 'age','sex','cp','thestbps','chol','restecg','fbs','thalach','exang','oldpeak','slope','ca','thal','label']

In [316]:
statlog_data.tail()

age  sex   cp  thestbps   chol  restecg  fbs  thalach  exang  oldpeak  \
265  52.0  1.0  3.0     172.0  199.0      1.0  0.0    162.0    0.0      0.5   
266  44.0  1.0  2.0     120.0  263.0      0.0  0.0    173.0    0.0      0.0   
267  56.0  0.0  2.0     140.0  294.0      0.0  2.0    153.0    0.0      1.3   
268  57.0  1.0  4.0     140.0  192.0      0.0  0.0    148.0    0.0      0.4   
269  67.0  1.0  4.0     160.0  286.0      0.0  2.0    108.0    1.0      1.5   

     slope   ca  thal  label  
265    1.0  0.0   7.0      1  
266    1.0  0.0   7.0      1  
267    2.0  0.0   3.0      1  
268    2.0  0.0   6.0      1  
269    2.0  3.0   3.0      2

In [317]:
statlog_data.head()

age  sex   cp  thestbps   chol  restecg  fbs  thalach  exang  oldpeak  \
0  70.0  1.0  4.0     130.0  322.0      0.0  2.0    109.0    0.0      2.4   
1  67.0  0.0  3.0     115.0  564.0      0.0  2.0    160.0    0.0      1.6   
2  57.0  1.0  2.0     124.0  261.0      0.0  0.0    141.0    0.0      0.3   
3  64.0  1.0  4.0     128.0  263.0      0.0  0.0    105.0    1.0      0.2   
4  74.0  0.0  2.0     120.0  269.0      0.0  2.0    121.0    1.0      0.2   

   slope   ca  thal  label  
0    2.0  3.0   3.0      2  
1    2.0  0.0   7.0      1  
2    1.0  0.0   7.0      2  
3    2.0  1.0   7.0      1  
4    1.0  1.0   3.0      1

In [318]:
statlog_data.label.replace(to_replace=1,value=0,inplace = True)
statlog_data.label.replace(to_replace=2,value=1,inplace = True)
cleveland_data.label.replace(to_replace=2,value=1,inplace=True)
cleveland_data.label.replace(to_replace=3,value=1,inplace=True)
cleveland_data.label.replace(to_replace=4,value=1,inplace=True)

In [348]:
cleveland_data.thal.replace(to_replace='?', value=3.0, inplace=True)
cleveland_data.thal.replace(to_replace='6.0', value=6.0, inplace=True)
cleveland_data.thal.replace(to_replace='3.0', value=3.0, inplace=True)
cleveland_data.thal.replace(to_replace='7.0', value=7.0, inplace=True)

In [349]:
cleveland_data.ca.replace(to_replace='0.0', value=0.0, inplace=True)
cleveland_data.ca.replace(to_replace='3.0', value=3.0, inplace=True)
cleveland_data.ca.replace(to_replace='2.0', value=2.0, inplace=True)
cleveland_data.ca.replace(to_replace='1.0', value=1.0, inplace=True)
cleveland_data.ca.replace(to_replace='?', value=0.0, inplace=True)

In [350]:
frames = [cleveland_data, statlog_data]

In [351]:
result = pd.concat(frames)

In [353]:
result.to_csv('combined_data.csv')

In [172]:
aa = np.array(result)

In [173]:
aa.shape

(573, 14)

In [321]:
y = pd.DataFrame(result.loc[:,result.columns=='label'])
x = pd.DataFrame(result.loc[:,result.columns!= 'label'])

In [322]:
print(x.shape)
print(y.shape)

(573, 13)
(573, 1)


In [327]:
print(x.thal.value_counts())
print(x.ca.value_counts())
print(np.unique(y))

3.0    320
7.0    221
6.0     32
Name: thal, dtype: int64
0.0    340
1.0    123
2.0     71
3.0     39
Name: ca, dtype: int64
[0 1]


In [217]:
mean = np.mode(x.thal)
print(mean)
x.thal.replace(to_replace=0.0, value=mean, inplace=True)

AttributeError: module 'numpy' has no attribute 'mode'

In [324]:

y.label.replace(to_replace=2,value=1,inplace = True)
y.label.replace(to_replace=3,value=1,inplace = True)
y.label.replace(to_replace=4,value=1,inplace = True)

In [325]:
x.thal.replace(to_replace='?', value=3.0, inplace=True)
x.thal.replace(to_replace='6.0', value=6.0, inplace=True)
x.thal.replace(to_replace='3.0', value=3.0, inplace=True)
x.thal.replace(to_replace='7.0', value=7.0, inplace=True)

In [326]:
x.ca.replace(to_replace='0.0', value=0.0, inplace=True)
x.ca.replace(to_replace='3.0', value=3.0, inplace=True)
x.ca.replace(to_replace='2.0', value=2.0, inplace=True)
x.ca.replace(to_replace='1.0', value=1.0, inplace=True)
x.ca.replace(to_replace='?', value=0.0, inplace=True)


In [162]:
np.unique(x.ca)

array([0., 1., 2., 3.])

In [340]:
x_train,x_test = train_test_split(x,test_size=0.2,random_state=0)
y_train, y_test = train_test_split(y, test_size=0.2,random_state=0)


In [341]:
print(x_train.shape , x_test.shape , x.shape)

(458, 13) (115, 13) (573, 13)


# SVM

In [330]:
model = svm.SVC(gamma='auto')
model.fit (x_train, y_train)
model.score(x_test, y_test)

C:\Users\MitTal\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.7444444444444445

In [105]:
x.thal.replace(to_replace='?', value=0.0, inplace=True)

In [106]:
x.thal.unique()

array([6.       , 3.       , 7.       , 4.7029703])

In [95]:
x.thal.replace(to_replace='6.0', value=6.0, inplace=True)
x.thal.replace(to_replace='3.0', value=3.0, inplace=True)
x.thal.replace(to_replace='7.0', value=7.0, inplace=True)

In [54]:
x.describe()

age         sex          cp    thestbps        chol     restecg  \
count  573.000000  573.000000  573.000000  573.000000  573.000000  573.000000   
mean    54.436300    0.678883    3.165794  131.527051  248.090750    0.148342   
std      9.063965    0.467314    0.954607   17.708934   51.710215    0.355749   
min     29.000000    0.000000    1.000000   94.000000  126.000000    0.000000   
25%     48.000000    0.000000    3.000000  120.000000  212.000000    0.000000   
50%     55.000000    1.000000    3.000000  130.000000  243.000000    0.000000   
75%     61.000000    1.000000    4.000000  140.000000  277.000000    0.000000   
max     77.000000    1.000000    4.000000  200.000000  564.000000    1.000000   

              fbs     thalach       exang     oldpeak       slope          ca  \
count  573.000000  573.000000  573.000000  573.000000  573.000000  573.000000   
mean     1.005236  149.640489    0.328098    1.044503    1.593368    0.666667   
std      0.995606   22.992319    0.469931    1.152631    0.614872    0.938058   
min      0.000000   71.000000    0.000000    0.000000    1.000000    0.000000   
25%      0.000000  133.000000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    2.000000    0.000000   
75%      2.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    3.000000    3.000000   

             thal  
count  573.000000  
mean     4.699825  
std      1.955077  
min      0.000000  
25%      3.000000  
50%      3.000000  
75%      7.000000  
max      7.000000

In [55]:
result.thal.value_counts()

3.0    166
3.0    152
7.0    117
7.0    104
6.0     18
6.0     14
?        2
Name: thal, dtype: int64

In [102]:
result.ca.unique()

array(['0.0', '3.0', '2.0', '1.0', '?', 3.0, 0.0, 1.0, 2.0], dtype=object)

In [162]:
result.ca.value_counts() 

0.0    176
0.0    160
1.0     65
1.0     58
2.0     38
2.0     33
3.0     20
3.0     19
?        4
Name: ca, dtype: int64

In [103]:
result.ca.replace(to_replace='0.0', value=0.0, inplace=True)
result.ca.replace(to_replace='3.0', value=3.0, inplace=True)
result.ca.replace(to_replace='2.0', value=2.0, inplace=True)
result.ca.replace(to_replace='1.0', value=1.0, inplace=True)


In [71]:
result.ca.unique()

array(['0.0', '3.0', '2.0', '1.0', '?', 3.0, 0.0, 1.0, 2.0], dtype=object)

In [105]:
result = result[result.thal !='?']


In [106]:
result= result[result.ca !='?']

# ANN

In [344]:
mlp = MLPClassifier(hidden_layer_sizes=9000, max_iter =200,random_state=0 , activation='logistic')
mlp.fit(x_train, y_train)
mlp.score(x_test, y_test)

C:\Users\MitTal\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.8347826086956521

In [286]:
confusion_matrix(y_test,predictedOutput)

array([[82,  6],
       [27,  0]], dtype=int64)

In [307]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB().fit(x_train,y_train)
accu = clf.score(x_train, y_train)
print(accu)

0.8796296296296297


C:\Users\MitTal\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [288]:
tree = DecisionTreeClassifier()
tree = tree.fit(x_train,y_train)
y_pred = tree.predict(x_test)
tree.score(x_test,y_test)

0.5478260869565217

In [361]:
clf = MLPClassifier()
print ('MLP: ',max(cross_val_score(clf, x, y, cv=20)))

clf = GaussianNB()
print ('Naive Bayes: ',np.max(cross_val_score(clf, x, y, cv=20)))

clf = DecisionTreeClassifier(random_state=0)
print ('Decision Trees: ',np.max(cross_val_score(clf, x, y, cv=20)))

MLP:  0.9655172413793104
Naive Bayes:  0.9310344827586207
Decision Trees:  1.0
